### ISSUE TITLE
Mysql driver placement, or how to finish puppet run before starting JIRA

### ISSUE THREAD

**Issue by zachdaniel** [brycejohnson/puppet-jira#45]
This question probably leaves much to be desired, and may be resolved simply with some puppet-fu.

We were receiving errors when starting JIRA in regards to a lack of mysql drivers.  We specified the driver in the `dbdriver` parameter as `com.mysql.jdbc.Driver`, but still ended up needing to add a driver(.jar) file to `<install_directory>/lib/`.  Due to the fact that JIRA module declares the directory where this needs to be placed, we can't place the file in the right place before running the JIRA module.  We do it afterwards then, but by the time we've placed the driver in the right place, JIRA has finished starting without that required file and is displaying a JIRALocked page.  So we are forced to stop JIRA, place the file, and start JIRA again.  But this means that our nightly puppet runs bounce our JIRA instance.  This could be solved by not needing to add the mysql driver, or by having a good way to ensure the service is running at the very end of the puppet run.

Any thoughts?

**Comment by mkrakowitzer** [comment]
I think this may be fixed if you use the github version of the module. Just
busy finishing some other minor updates and plan to push a new version to
the forge which hopefully will fix this for you.

Let me know if that works, if not I'll take a look.

**Comment by zachdaniel** [comment]
Thanks!  I'll wait for the forge update and give it a shot.

**Comment by mkrakowitzer** [comment]
I have pushed a new version to the forge. Please let me know if it solved your problem.

If have the time, please consider rating the puppet jira module on the forge :)

**Comment by mkrakowitzer** [comment]
Hi Zach

I have been testing the mysql connector on various operating systems.
Both CentOS 6 and Ubuntu 12.04 have this issue: http://bugs.mysql.com/bug.php?id=61201.

MySQL Connector 5.1.16 and 5.1.17 is known not to work with most atlassian products:  Ubuntu 12.04 ships 5.1.16. Centos 6 with 5.1.17.

**Comment by zachdaniel** [comment]
I suspect I'm doing this wrong, but no matter how I configure it I'm getting the Tomcat error 'could not determine database type'

```  class { '::jira':
    version        => $version,
    installdir     => $install_dir,
    homedir        => $home_dir,
    db             => 'mysql',
    dbuser         => $dbuser,
    dbpassword     => $dbpassword,
    dbserver       => $dbserver,
    dbname         => $dbname,
    dbport         => $dbport,
    dbtype         => 'mysql',
    dbdriver       => 'com.mysql.jdbc.Driver',
    javahome       => '/usr/java/latest/',
    jvm_xmx        => '3584m',
    jvm_permgen    => '3584m',
    require        => File[$install_dir],
    service_ensure => 'running',
    java_opts      => '-Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true',
  }```

**Comment by zachdaniel** [comment]
I've tried it without dbdriver set, but I see no evidence of it managing or installing any mysql drivers.

**Comment by zachdaniel** [comment]
I think I had a misconception here.  I realize now the option to select a jar was all I needed.  I just placed the jar before-hand, and pointed to it during the installation.  Sorry for the confusion, I would consider this issue addressed, seeing as the MySQL Connector package for CentOS is the reason it wasn't working earlier, not your module.

**Comment by mkrakowitzer** [comment]
Hi Zach, 

Glad its working, I added a new feature this weekend to download the latest driver and correctly place it. Its not uploaded to the forge yet though. I have just finished testing it on Ubuntu 12.04/14.04/Centos67 and Debian. 

I hope to release 1.1.5 this week, just adding some other small features first.

**Comment by mkrakowitzer** [comment]
Please consider rating the module on puppet forge if you have time :)

**Comment by zachdaniel** [comment]
Just rated the other day.  The module has been a lifesaver in the process of moving from a modified WAR version of JIRA to a standalone.
